[tool.poetry]
name = "prompt_to_video"
version = "1.0.0"
description = "Example template for Python applications"
authors = ["Marius Arlauskas", "Tomas Timinskas"]
readme = "README.md"
package-mode = true

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.dependencies]
python = "~3.12"
diffusers = "^0.31.0"
transformers = "^4.46.0"
accelerate = "^1.0.1"
safetensors = "^0.4.5"
protobuf = "^5.28.3"
sentencepiece = "^0.2.0"
openai = "^1.54.3"
pydantic = "^2.9.2"
streamlit = "^1.40.0"
torch = "^2.5.1"
pillow = ">=9.2.0,<11.0.0"
moviepy = "2.0.0.dev2"
pydub = "^0.25.1"
srt = "^3.5.3"
edge-tts = { git = "https://github.com/rany2/edge-tts.git" }
ffmpeg-python = "^0.2.0"
mosaico = "0.1.0rc7"
mutagen = "^1.47.0"

[tool.poetry.group.development.dependencies]
python-dotenv = "^1.0.1"
ruff = "^0.9.5"
pytest = "^8.3.4"
pickleshare = "^0.7.5"
ipykernel = "^6.29.5"
isort = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN002",  # Missing type annotation for args
  "ANN003",  # Missing type annotation for kwarg
  "ANN401",  # Dynamic type annotations
  "COM812",  # Missing trailing comma
  "D100",    # Missing docstring in public module
  "D101",    # Missing docstring in public class (for obvious classes)
  "D103",    # Missing docstring in public function (for obvious functions)
  "D104",    # Missing docstring in public package
  "FBT001",  # Bool use in arg
  "FBT002",  # Default bool use in arg
  "G004",    # Logging with f-strings
  "INP001",  # Missing __init__.py in package
  "PLR0913", # Too many arguments (ignored if default args are used)
  "S101",    # Use of assert
  "SLF001",  # Access to a private member (for tests only)
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"